import {
    Home,
    User,
    Settings,
    LogOut,
    Bell,
    Menu,
    ScrollText,
    Search,
    Wheat,
    PillBottle,
    CloudRain,
    CircleAlert,
    PawPrint,
    Scale,
    DollarSign,
    HandCoins,
    Save,
    Handshake,
} from 'lucide-react-native'

export const Icons = {
    home: Home,
    user: User,
    settings: Settings,
    logout: LogOut,
    bell: Bell,
    menu: Menu,
    contract: ScrollText,
    search: Search,
    wheat: Wheat,
    supplementation: PillBottle,
    forragem: CloudRain,
    circleAlert: CircleAlert,
    pawPrint: PawPrint,
    scale: Scale,
    dolar: DollarSign,
    handCoins: HandCoins,
    save: Save,
    handShake: Handshake,
}