import {
    Home,
    User,
    Settings,
    LogOut,
    Bell,
    Menu,
    ScrollText,
    Search,
    Wheat,
    PillBottle,
    CloudRain,
    CircleAlert,
    CircleMinus,
    CircleDotDashed,
    PawPrint,
    Scale,
    DollarSign,
    HandCoins,
    Save,
    Handshake,
    FlaskConical,
    MilkOff,
    Clipboard,
    TrendingUp,
    ChartColumn,
    FileText,
    BrushCleaning,
    Trash2,
    Eye,
    EyeOff,
} from 'lucide-react-native'

export const Icons = {
    home: Home,
    user: User,
    settings: Settings,
    logout: LogOut,
    bell: Bell,
    menu: Menu,
    contract: ScrollText,
    search: Search,
    wheat: Wheat,
    supplementation: PillBottle,
    forragem: CloudRain,
    circleAlert: CircleAlert,
    circleMinus: CircleMinus,
    circleDotDashed: CircleDotDashed,
    pawPrint: PawPrint,
    scale: Scale,
    dolar: DollarSign,
    handCoins: HandCoins,
    save: Save,
    handShake: Handshake,
    flaskConical: FlaskConical,
    notFoundBottle: MilkOff,
    clipBoard: Clipboard,
    trendingUp: TrendingUp,
    graphic: ChartColumn,
    fileText: FileText,
    brushCleaning: BrushCleaning,
    trash: Trash2,
    eye: Eye,
    eyeOff: EyeOff,
}